name: Automation

on: 
  workflow_dispatch

jobs:
  orchestrator:
    runs-on: ubuntu-latest
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run:  pip install "typer>=0.27" "databricks-sdk>=0.17" rich
      - name: Run orchestrator.py
        run: python Lab9/orchestrator.py run --job entsoe-unit-tests-prod